export const metadata = {
  title: 'Study365',
  description: 'Generated by Next.js',
}
import '@/styles/global.css'
import Header from '@/components/Header'


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
