

import type { Metadata } from 'next'
import HeaderStudent from '@/app/_components/Header/HeaderStudent'


export const metadata: Metadata = {
  title: 'Study365',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className="layout-sticky-subnav layout-default">
        <HeaderStudent />

        {children}
      </body>
    </html>
  )
}
